spring:
  profiles:
    include:
      - database
      - springdoc
      - jwt
      - redis
      - s3
      - mail
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart: # MULTIPART (MultipartProperties) Enable support of multipart uploads.
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org.hibernate.SQL: debug
  org.springframework.core.LocalVariableTableParameterNameDiscoverer : error