spring:
  profiles:
    include:
      - database
      - springdoc
      - jwt
      - redis
      - s3
      - mail
      - payment
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart: # MULTIPART (MultipartProperties) Enable support of multipart uploads.
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false

  security:
    user:
      name: user
      password: 1111

logging.level:
  org.hibernate.SQL: debug
  org.springframework.core.LocalVariableTableParameterNameDiscoverer : error