spring:
  profiles:
    include:
      - springdoc
      - jwt
      - redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart: # MULTIPART (MultipartProperties) Enable support of multipart uploads.
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    ### DBCP( Database Connection Pool )
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug


# CORS
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Content-Type,Authorization
  allow-credentials: true
  max-age: 3600

# AWS S3
cloud:
  aws:
    credentials:
      access-key: S3_ACCESS_KEY
      secret-key: S3_SECRET_KEY
    s3:
      bucket: S3_BUCKET_NAME
      url: S3_BUCKET_URL
      dir: /img
    region:
      static: S3_REGION
    stack:
      auto: false