name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        ## create application-database.yml
      - name: make application-database.yml
        run: |
          # create application-database.yml
          cd ./src/main/resources
          
          # application-database.yaml 파일 생성
          touch ./application-database.yml
          
          # GitHub-Actions 에서 설정한 값을 application-database.yaml 파일에 쓰기
          echo "${{ secrets.DATABASE }}" >> ./application-database.yml
        shell: bash

      - name: make application-redis.yml
        run: |
          # create application-redis.yml
          cd ./src/main/resources

          # application-redis.yaml 파일 생성
          touch ./application-redis.yml

          # GitHub-Actions 에서 설정한 값을 application-redis.yaml 파일에 쓰기
          echo "${{ secrets.REDIS }}" >> ./application-redis.yml
        shell: bash


      - name: Build with Gradle
        run: |
          chmod +x gradlew 
          ./gradlew build
#          ./gradlew bootJar
      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/shopping-mall . 
          docker push ${{ secrets.DOCKER_REPO }}/shopping-mall
      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/shopping-mall
            docker-compose up -d
            sudo docker image prune -f
